
INSULT_1 = [
    'lazy ',
    'stupid ',
    'slimy ',
    'slutty ',
    'smelly ',
    'pompous ',
    'communist ',
    'dicknose ',
    'pie-eating ',
    'racist ',
    'white trash ',
    'drug-loving ',
    'butterface ',
    'tone deaf ',
    'creepy ',
    'insecure ',
    'idiotic ',
    'elitist ',
    'ugly '
]

INSULT_2 = [
    'douche ',
    'ass ',
    'turd ',
    'rectum ',
    'butt ',
    'cock ',
    'shit ',
    'crotch ',
    'bitch ',
    'turd ',
    'prick ',
    'slut ',
    'taint ',
    'fuck ',
    'dick ',
    'boner ',
    'shart ',
    'nut ',
    'sphincter'
]

INSULT_3 = [
    'pilot',
    'canoe',
    'captain',
    'pirate',
    'hammer',
    'knob',
    'box',
    'jockey',
    'nazi',
    'waffle',
    'goblin',
    'blossum',
    'biscuit',
    'clown',
    'socket',
    'monster',
    'hound',
    'dragon',
    'balloon'
]
